# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0002_auto_20161107_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='Item.Item'),
        ),
    ]
