# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
