# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 22:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='id',
        ),
        migrations.AlterField(
            model_name='seller',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='is_seller', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
