# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
