# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='bid',
        ),
        migrations.AddField(
            model_name='biditem',
            name='item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='Item.Item'),
        ),
        migrations.AlterField(
            model_name='biditem',
            name='action_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='childID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentID', to='Item.Category'),
        ),
    ]
