# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-01 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='bid',
        ),
        migrations.AddField(
            model_name='item',
            name='action_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='current_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='reserved_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='listed_price',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='BidItem',
        ),
    ]
