# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0002_auto_20161011_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biditem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='Item.Item', unique=True),
        ),
    ]
