# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0003_biditem_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parentID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Item.Category'),
        ),
    ]
