# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0004_auto_20161107_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='Item.Category'),
            preserve_default=False,
        ),
    ]
