# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0006_rate_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description_short',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
