# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0011_auto_20161214_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='provider',
        ),
    ]
